# Generated by Django 5.1.7 on 2025-03-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تایتل')),
                ('icons', models.ImageField(blank=True, null=True, upload_to='About/', verbose_name='عکس')),
            ],
        ),
    ]
